language: python

env:
  DATABASE_URL="dbname='questioner' host='127.0.0.1' port='5432' user='leewel' password='root'"
  DATABASE_TESTING_URL="dbname='questionertest' host='127.0.0.1' port='5432' user='leewel' password='root'"

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls 

services:
  - postgresql

addons:
  postgresql: "9.6"

env:
  global:
  - PGPORT=5432

before_script:

  - psql -c 'create database questioner;' -U postgres
  - psql -c "create user leewel with password 'root';"
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to leewel ;" -U postgres

script:
 - pytest --cov app/tests/v1

after_success:
 - coveralls
 
